#!/bin/bash
path() {
    echo "/../certificats/" #where the certificat.p12 file is located
}

openssl_certificat()
{
	pathCertificats="$(path)"
	echo "Connect to the path... $pathCertificats"
	openssl pkcs12 -in "$pathCertificats""$1" -clcerts -nokeys -out "$pathCertificats""$2""/fileName.crt" -passin pass:passwd
	openssl pkcs12 -in "$pathCertificats""$1" -nocerts -nodes -out "$pathCertificats""$2""/fileName.key" -passin pass:passwd
	echo "openssl certificat is created with success"
	return
}
openssl_certificat $1 $2

#$1 certificat file name *.p12
#$2 the folder where you want to put the .crt and .key file
